name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'  # Specify the Flutter version you are using

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests with coverage
      run: |
        flutter test --coverage
        # Optionally, you can upload the coverage report to a service like Codecov or Coveralls
        # For example, if you use Codecov:
        # bash <(curl -s https://codecov.io/bash) -t YOUR_CODECOV_TOKEN

    - name: Analyze code
      run: flutter analyze

    - name: Build APK
      run: flutter build apk --release

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage/lcov.info
