name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: dart-lang/setup-dart@v2
      with:
        sdk: stable
        flutter: true

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests with coverage
      run: |
        flutter test --coverage
        # Optionally, you can upload the coverage report to a service like Codecov or Coveralls
        # For example, if you use Codecov:
        # bash <(curl -s https://codecov.io/bash) -t YOUR_CODECOV_TOKEN

    - name: Analyze code
      run: flutter analyze

    - name: Build APK
      run: flutter build apk --release

    # - name: Build iOS
    #   run: flutter build ios --release
      # Note: Building for iOS typically requires a macOS runner
      # You might need to adjust or add this step based on your CI environment

    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage/lcov.info
